# Generated by Django 3.2.10 on 2022-03-27 16:22

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import repertoire.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, unique=True)),
                ('seats', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seans',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seats', models.JSONField(default=repertoire.models.default_seats_dict)),
                ('slug', models.SlugField(blank=True, default='automaticly-filled')),
                ('showingDate', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date.today)])),
                ('futureDays', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('hall', models.ForeignKey(help_text='Wybierz salę w której odbędzie się seans', on_delete=django.db.models.deletion.CASCADE, to='repertoire.hall')),
                ('movie', models.ForeignKey(help_text='Wybierz film, który będzie seansem', on_delete=django.db.models.deletion.CASCADE, to='library.movie')),
                ('showingHour', models.ForeignKey(help_text='Wybierz godzinę projekcji filmu', on_delete=django.db.models.deletion.CASCADE, to='repertoire.time')),
            ],
            options={
                'verbose_name': 'Showing',
                'verbose_name_plural': 'Showings',
            },
        ),
        migrations.AddConstraint(
            model_name='seans',
            constraint=models.UniqueConstraint(fields=('movie', 'hall', 'showingDate', 'showingHour'), name='showing_contraints'),
        ),
        migrations.AddConstraint(
            model_name='seans',
            constraint=models.UniqueConstraint(fields=('hall', 'showingDate', 'showingHour'), name='same_hall_date_showing'),
        ),
    ]
