# Generated by Django 3.2.10 on 2022-04-13 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0002_cinema'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='cinema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='repertoire.cinema'),
        ),
    ]
