# Generated by Django 3.2.10 on 2022-04-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0003_hall_cinema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddConstraint(
            model_name='hall',
            constraint=models.UniqueConstraint(fields=('name', 'cinema'), name='same_name_cinema'),
        ),
    ]
