# Generated by Django 3.2.10 on 2022-04-20 16:08

from django.db import migrations, models
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0004_auto_20220413_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
