import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTesty():
  def setup_method(self, method):
    self.driver = webdriver.Edge()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_111PoprawnaRejestracja(self):
    self.driver.maximize_window()
    self.driver.get("http://127.0.0.1:8000/repertoire/")
    WebDriverWait(self.driver, 3000).until(expected_conditions.presence_of_element_located((By.ID, "cinemaSelector")))
    self.driver.find_element(By.ID, "cinemaSelector").click()
    dropdown = self.driver.find_element(By.ID, "cinemaSelector")
    dropdown.find_element(By.XPATH, "/html/body/header/nav/div/div/ul[2]/li[1]/form/a/select/option[2]").click()
  
    self.driver.find_element(By.ID, "SignIn").click()
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("jekapiotr")
    self.driver.find_element(By.ID, "id_email").send_keys("testjekapiotr@gmail.com")
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(3)").click()
    self.driver.find_element(By.ID, "id_password").click()
    self.driver.find_element(By.ID, "id_password").send_keys("Jekapiotr33@")
    self.driver.find_element(By.ID, "id_password2").click()
    self.driver.find_element(By.ID, "id_password2").send_keys("Jekapiotr33@")
    self.driver.find_element(By.CSS_SELECTOR, ".bg-secondary").click()
    self.driver.find_element(By.CSS_SELECTOR, "h1").click()
    self.driver.find_element(By.ID, "LogIn").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "id_username").send_keys("admin")
    self.driver.find_element(By.ID, "id_password").click()
    self.driver.find_element(By.ID, "id_password").send_keys("Koperek!1")
    self.driver.find_element(By.CSS_SELECTOR, ".bg-secondary").click()
    self.driver.find_element(By.ID, "AdminPanel").click()
    self.driver.find_element(By.LINK_TEXT, "Users").click()
    self.driver.find_element(By.ID, "searchbar").click()
    self.driver.find_element(By.ID, "searchbar").send_keys("jekapiotr")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(3)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) > .field-username").text == "jekapiotr"
    assert self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) > .field-email").text == "testjekapiotr@gmail.com"
    self.driver.find_element(By.NAME, "_selected_action").click()
    self.driver.find_element(By.NAME, "action").click()
    dropdown = self.driver.find_element(By.NAME, "action")
    dropdown.find_element(By.XPATH, "//option[. = 'Delete selected users']").click()
    self.driver.find_element(By.NAME, "index").click()
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(4)").click()
    self.driver.find_element(By.LINK_TEXT, "REPERTUAR").click()

  def test_112BdnarejestracjaBdnyadresemail(self):
    self.driver.maximize_window()
    self.driver.get("http://127.0.0.1:8000/repertoire/")

    self.driver.find_element(By.ID, "SignIn").click()
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("jekapiotr")
    self.driver.find_element(By.ID, "id_email").click()
    self.driver.find_element(By.ID, "id_email").send_keys("testjekapiotr.com")
    self.driver.find_element(By.ID, "id_password").click()
    self.driver.find_element(By.ID, "id_password").send_keys("Jekapiotr99@")
    self.driver.find_element(By.ID, "id_password2").send_keys("Jekapiotr99@")
    self.driver.find_element(By.CSS_SELECTOR, ".bg-secondary").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".errorlist > li").text == "Wprowadź poprawny adres e-mail."
  
  def test_113BdnarejestracjaKrtkiehaso(self):
    self.driver.maximize_window()
    self.driver.get("http://127.0.0.1:8000/repertoire/")

    self.driver.find_element(By.ID, "SignIn").click()
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("jekapiotr")
    self.driver.find_element(By.ID, "id_email").click()
    self.driver.find_element(By.ID, "id_email").send_keys("testjekapiotr@gmail.com")
    self.driver.find_element(By.ID, "id_password").click()
    self.driver.find_element(By.ID, "id_password").send_keys("Jekapio")
    self.driver.find_element(By.ID, "id_password2").send_keys("Jekapio")
    self.driver.find_element(By.CSS_SELECTOR, ".bg-secondary").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".errorlist > li").text == "Hasło powinno mieć conajmniej 8 znaków."
  
  def test_114BdnarejestracjaBrakhasa(self):
    self.driver.maximize_window()
    self.driver.get("http://127.0.0.1:8000/repertoire/")

    self.driver.find_element(By.ID, "SignIn").click()
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("jekapiotr1")
    self.driver.find_element(By.ID, "id_email").click()
    self.driver.find_element(By.ID, "id_email").send_keys("testjekapiotr@gmail.com")
    self.driver.find_element(By.CSS_SELECTOR, ".bg-secondary").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".errorlist:nth-child(8) > li").text == "To pole jest wymagane."
    assert self.driver.find_element(By.CSS_SELECTOR, ".errorlist:nth-child(5) > li").text == "To pole jest wymagane."
  
  def test_115PowielonaRejestracja(self):
    self.driver.maximize_window()
    self.driver.get("http://127.0.0.1:8000/repertoire/")

    self.driver.find_element(By.ID, "SignIn").click()
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("admin")
    self.driver.find_element(By.ID, "id_email").click()
    self.driver.find_element(By.ID, "id_email").send_keys("testjekapiotr@gmail.com")
    self.driver.find_element(By.ID, "id_password").click()
    self.driver.find_element(By.ID, "id_password").send_keys("Jekapiotr33@")
    self.driver.find_element(By.ID, "id_password2").click()
    self.driver.find_element(By.ID, "id_password2").send_keys("Jekapiotr33@")
    self.driver.find_element(By.CSS_SELECTOR, ".bg-secondary").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".errorlist > li").text == "Użytkownik o tej nazwie już istnieje."

  def test_121Logowanieprzyuyciuadresuemail(self):
    self.driver.maximize_window()
    self.driver.get("http://127.0.0.1:8000/repertoire/")

    self.driver.find_element(By.ID, "LogIn").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("jekapiotr@gmail.com")
    self.driver.find_element(By.ID, "id_password").send_keys("Jekapiotr66@")
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)
    assert self.driver.find_element(By.ID, "UserCard").text == "WITAJ JEKAPIOTR2"
    self.driver.find_element(By.ID, "LogOut").send_keys(Keys.ENTER)
  
  def test_122Logowanieprzyuyciuloginu(self):
    self.driver.maximize_window()
    self.driver.get("http://127.0.0.1:8000/repertoire/")

    self.driver.find_element(By.ID, "LogIn").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("jekapiotr2")
    self.driver.find_element(By.ID, "id_password").send_keys("Jekapiotr66@")
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)
    assert self.driver.find_element(By.ID, "UserCard").text == "WITAJ JEKAPIOTR2"
    self.driver.find_element(By.ID, "LogOut").send_keys(Keys.ENTER)
  
  def test_124Bdnelogowanieprzyuyciumaila(self):
    self.driver.maximize_window()
    self.driver.get("http://127.0.0.1:8000/repertoire/")

    self.driver.find_element(By.ID, "LogIn").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("jekapiotr@gmail.com")
    self.driver.find_element(By.ID, "id_password").click()
    self.driver.find_element(By.ID, "id_password").send_keys("password")
    self.driver.find_element(By.CSS_SELECTOR, ".bg-secondary").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".item > p").text == "Twoja nazwa użytkownika lub hasło nie pasują. Spróbuj zalogować się jeszcze raz."

  def test_125Bdnelogowanieprzyuyciuloginu(self):
    self.driver.maximize_window()
    self.driver.get("http://127.0.0.1:8000/repertoire/")

    self.driver.find_element(By.ID, "LogIn").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("piotr")
    self.driver.find_element(By.ID, "id_password").click()
    self.driver.find_element(By.ID, "id_password").send_keys("password")
    self.driver.find_element(By.CSS_SELECTOR, ".bg-secondary").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".item > p").text == "Twoja nazwa użytkownika lub hasło nie pasują. Spróbuj zalogować się jeszcze raz."
 
  def test_141ElementyDashboardu(self):
    self.driver.maximize_window()
    self.driver.get("http://127.0.0.1:8000/repertoire/")

    self.driver.find_element(By.ID, "LogIn").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("jekapiotr2")
    self.driver.find_element(By.ID, "id_password").click()
    self.driver.find_element(By.ID, "id_password").send_keys("Jekapiotr66@")
    self.driver.find_element(By.CSS_SELECTOR, ".bg-secondary").click()
    self.driver.find_element(By.ID, "UserCard").send_keys(Keys.ENTER)
    assert self.driver.find_element(By.LINK_TEXT, "Zmień swoje hasło").text == "Zmień swoje hasło"
    assert self.driver.find_element(By.LINK_TEXT, "Zmień swój adres email").text == "Zmień swój adres email"
    assert self.driver.find_element(By.LINK_TEXT, "Deaktywuj swoje konto").text == "Deaktywuj swoje konto"
    self.driver.find_element(By.ID, "LogOut").send_keys(Keys.ENTER)
   
  def test_151351Poprawnewystawienieopinii(self):
    self.driver.maximize_window()
    self.driver.get("http://127.0.0.1:8000/repertoire/")
    WebDriverWait(self.driver, 3000).until(expected_conditions.presence_of_element_located((By.ID, "cinemaSelector")))
    self.driver.find_element(By.ID, "cinemaSelector").click()
    dropdown = self.driver.find_element(By.ID, "cinemaSelector")
    dropdown.find_element(By.XPATH, "/html/body/header/nav/div/div/ul[2]/li[1]/form/a/select/option[2]").click()
    self.driver.find_element(By.ID, "LogIn").send_keys(Keys.ENTER)

    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("JanKowalski")
    self.driver.find_element(By.ID, "id_password").send_keys("Qwerty123")
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)

    WebDriverWait(self.driver, 1000).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "a > .card-img-top")))
    self.driver.find_element(By.CSS_SELECTOR, "a > .card-img-top").click()
    self.driver.execute_script("window.scrollTo(0, 1080)")
    WebDriverWait(self.driver, 4000).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "#review > i:nth-child(4)")))

    element_to_hover_over = self.driver.find_element(By.CSS_SELECTOR, "#review > i:nth-child(4)")
    hover = ActionChains(self.driver).move_to_element(element_to_hover_over)
    hover.perform()

    self.driver.find_element(By.CSS_SELECTOR, "#review > i:nth-child(4)").click()
    WebDriverWait(self.driver, 2000).until(expected_conditions.element_to_be_clickable((By.XPATH, "/html/body/div/div[2]/div[3]/form/div[2]/textarea")))
    self.driver.find_element(By.XPATH, "/html/body/div/div[2]/div[3]/form/div[2]/textarea").clear()
    self.driver.find_element(By.XPATH, "/html/body/div/div[2]/div[3]/form/div[2]/textarea").send_keys("Film nienajgorszy!")
    self.driver.find_element(By.CSS_SELECTOR, ".textRatingSend").send_keys(Keys.ENTER)
    assert self.driver.find_element(By.CSS_SELECTOR, ".opinion:nth-child(2) .opinionHeader").text == "Użytkownik JanKowalski ocenił(a) film na  "
    assert self.driver.find_element(By.CSS_SELECTOR, ".opinion:nth-child(2) > div:nth-child(2)").text == "Film nienajgorszy!"
    self.driver.find_element(By.ID, "LogOut").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "LogIn").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "id_username").send_keys("admin")
    self.driver.find_element(By.ID, "id_password").send_keys("Koperek!1")
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "AdminPanel").click() 
    self.driver.find_element(By.LINK_TEXT, "User opinions").click()
    self.driver.find_element(By.NAME, "_selected_action").click()
    self.driver.find_element(By.NAME, "action").click()
    dropdown = self.driver.find_element(By.NAME, "action")
    dropdown.find_element(By.XPATH, "//option[. = 'Delete selected user opinions']").click()
    self.driver.find_element(By.NAME, "index").click()
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(4)").click()
     
  def test_154354Edytowanieopinii(self):
    self.driver.maximize_window()
    self.driver.get("http://127.0.0.1:8000/repertoire/")
    WebDriverWait(self.driver, 3000).until(expected_conditions.presence_of_element_located((By.ID, "cinemaSelector")))
    self.driver.find_element(By.ID, "cinemaSelector").click()
    dropdown = self.driver.find_element(By.ID, "cinemaSelector")
    dropdown.find_element(By.XPATH, "/html/body/header/nav/div/div/ul[2]/li[1]/form/a/select/option[2]").click()

    self.driver.find_element(By.ID, "LogIn").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("JanKowalski")
    self.driver.find_element(By.ID, "id_password").send_keys("Qwerty123")
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, "a > .card-img-top").click()
    self.driver.execute_script("window.scrollTo(0, 1080)")
    WebDriverWait(self.driver, 4000).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "#review > i:nth-child(4)")))

    element_to_hover_over = self.driver.find_element(By.CSS_SELECTOR, "#review > i:nth-child(4)")
    hover = ActionChains(self.driver).move_to_element(element_to_hover_over)
    hover.perform()

    self.driver.find_element(By.CSS_SELECTOR, "#review > i:nth-child(4)").click()
    self.driver.find_element(By.ID, "textRating").send_keys("Film nienajgorszy!")
    self.driver.find_element(By.CSS_SELECTOR, ".textRatingSend").send_keys(Keys.ENTER)
    assert self.driver.find_element(By.CSS_SELECTOR, ".opinion:nth-child(2) .opinionHeader").text == "Użytkownik JanKowalski ocenił(a) film na  "
    assert self.driver.find_element(By.CSS_SELECTOR, ".opinion:nth-child(2) > div:nth-child(2)").text == "Film nienajgorszy!"
    self.driver.find_element(By.ID, "textRating").send_keys(" ")
    self.driver.find_element(By.ID, "textRating").clear()
    self.driver.find_element(By.ID, "textRating").send_keys("Film w porządku!")
    self.driver.find_element(By.CSS_SELECTOR, ".textRatingSend").send_keys(Keys.ENTER)
    assert self.driver.find_element(By.CSS_SELECTOR, ".opinion:nth-child(2) .opinionHeader").text == "Użytkownik JanKowalski ocenił(a) film na  "
    assert self.driver.find_element(By.CSS_SELECTOR, ".opinion:nth-child(2) > div:nth-child(2)").text == "Film w porządku!"
    self.driver.find_element(By.ID, "LogOut").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "LogIn").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "id_username").send_keys("admin")
    self.driver.find_element(By.ID, "id_password").send_keys("Koperek!1")
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "AdminPanel").click()
    self.driver.find_element(By.LINK_TEXT, "User opinions").click()
    self.driver.find_element(By.NAME, "_selected_action").click()
    self.driver.find_element(By.NAME, "action").click()
    dropdown = self.driver.find_element(By.NAME, "action")
    dropdown.find_element(By.XPATH, "//option[. = 'Delete selected user opinions']").click()
    self.driver.find_element(By.NAME, "index").click()
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(4)").click()

  def test_161Zmianahasakonta(self):
    self.driver.maximize_window()
    self.driver.get("http://127.0.0.1:8000/repertoire/")

    self.driver.find_element(By.ID, "LogIn").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "id_username").send_keys("jekapiotr5")
    self.driver.find_element(By.ID, "id_password").click()
    self.driver.find_element(By.ID, "id_password").send_keys("StareHasło33")
    self.driver.find_element(By.CSS_SELECTOR, ".bg-secondary").click()
    self.driver.find_element(By.ID, "UserCard").send_keys(Keys.ENTER)
    self.driver.find_element(By.LINK_TEXT, "Zmień swoje hasło").click()
    self.driver.find_element(By.ID, "id_old_password").send_keys("StareHasło33")
    self.driver.find_element(By.ID, "id_new_password1").send_keys("NoweHaslo33")
    self.driver.find_element(By.ID, "id_new_password2").send_keys("NoweHaslo33")
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(4)").click()
    self.driver.find_element(By.ID, "myBtn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-accept").click()
    self.driver.find_element(By.ID, "LogOut").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "LogIn").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "id_username").send_keys("jekapiotr5")
    self.driver.find_element(By.ID, "id_password").send_keys("StareHasło33")
    self.driver.find_element(By.CSS_SELECTOR, ".bg-secondary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".item > p").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".item > p").text == "Twoja nazwa użytkownika lub hasło nie pasują. Spróbuj zalogować się jeszcze raz."
    self.driver.find_element(By.ID, "id_password").send_keys("NoweHaslo33")
    self.driver.find_element(By.CSS_SELECTOR, ".bg-secondary").click()
    self.driver.find_element(By.ID, "UserCard").send_keys(Keys.ENTER)
    self.driver.find_element(By.LINK_TEXT, "Zmień swoje hasło").click()
    self.driver.find_element(By.ID, "id_old_password").send_keys("NoweHaslo33")
    self.driver.find_element(By.ID, "id_new_password1").send_keys("StareHasło33")
    self.driver.find_element(By.ID, "id_new_password2").send_keys("StareHasło33")
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(4)").click()
    self.driver.find_element(By.ID, "myBtn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-accept").click()
    self.driver.find_element(By.CSS_SELECTOR, ".py-2").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "h1").text == "Hasło zmienione"
    self.driver.find_element(By.ID, "LogOut").send_keys(Keys.ENTER)
  
  def test_172ZmianaAdresuEmailzbednymidanymibdnehaso(self):
    self.driver.maximize_window()
    self.driver.get("http://127.0.0.1:8000/repertoire/")

    self.driver.find_element(By.ID, "LogIn").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "id_username").send_keys("JanKowalski")
    self.driver.find_element(By.ID, "id_password").click()
    self.driver.find_element(By.ID, "id_password").send_keys("Qwerty123")
    self.driver.find_element(By.CSS_SELECTOR, ".bg-secondary").click()
    self.driver.find_element(By.ID, "UserCard").send_keys(Keys.ENTER)
    self.driver.find_element(By.LINK_TEXT, "Zmień swój adres email").click()
    self.driver.find_element(By.ID, "id_email1").click()
    self.driver.find_element(By.ID, "id_email1").send_keys("jankowalski3@wp.pl")
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(2)").click()
    self.driver.find_element(By.ID, "id_email2").click()
    self.driver.find_element(By.ID, "id_email2").send_keys("jankowalski3@wp.pl")
    self.driver.find_element(By.ID, "id_password").click()
    self.driver.find_element(By.ID, "id_password").send_keys("Qwer")
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(4)").click()
    self.driver.find_element(By.ID, "myBtn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-accept").click()
    self.driver.find_element(By.CSS_SELECTOR, ".cm > p:nth-child(4)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".cm > p:nth-child(4)").text == "Błędne hasło."
    self.driver.find_element(By.ID, "LogOut").send_keys(Keys.ENTER)
  
  def test_171ZmianaAdresuEmailzpoprawnymidanymi(self):
    self.driver.maximize_window()
    self.driver.get("http://127.0.0.1:8000/repertoire/")

    self.driver.find_element(By.ID, "LogIn").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("JanKowalski")
    self.driver.find_element(By.ID, "id_password").click()
    self.driver.find_element(By.ID, "id_password").send_keys("Qwerty123")
    self.driver.find_element(By.CSS_SELECTOR, ".bg-secondary").click()
    self.driver.find_element(By.ID, "UserCard").send_keys(Keys.ENTER)
    self.driver.find_element(By.LINK_TEXT, "Zmień swój adres email").click()
    self.driver.find_element(By.ID, "id_email1").send_keys("jankowalski2@wp.pl")
    self.driver.find_element(By.ID, "id_email2").send_keys("jankowalski2@wp.pl")
    self.driver.find_element(By.ID, "id_password").send_keys("Qwerty123")
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(4)").click()
    self.driver.find_element(By.ID, "myBtn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-accept").click()
    self.driver.find_element(By.ID, "LogOut").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "LogIn").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "id_username").clear()
    self.driver.find_element(By.ID, "id_username").send_keys("jankowalski@wp.pl")
    self.driver.find_element(By.ID, "id_password").send_keys("Qwerty123")
    self.driver.find_element(By.CSS_SELECTOR, ".bg-secondary").click()
    self.driver.find_element(By.ID, "id_username").clear()
    self.driver.find_element(By.ID, "id_username").send_keys("jankowalski2@wp.pl")
    self.driver.find_element(By.ID, "id_password").send_keys("Qwerty123")
    self.driver.find_element(By.CSS_SELECTOR, ".bg-secondary").click()
    self.driver.find_element(By.ID, "UserCard").send_keys(Keys.ENTER)
    WebDriverWait(self.driver, 3000).until(expected_conditions.visibility_of_element_located((By.LINK_TEXT, "Zmień swój adres email")))
    self.driver.find_element(By.LINK_TEXT, "Zmień swój adres email").click()
    self.driver.find_element(By.CSS_SELECTOR, "form > p:nth-child(1)").click()
    self.driver.find_element(By.ID, "id_email1").send_keys("jankowalski@wp.pl")
    self.driver.find_element(By.CSS_SELECTOR, "form > p:nth-child(1)").click()
    self.driver.find_element(By.ID, "id_email2").send_keys("jankowalski@wp.pl")
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, "form > p:nth-child(3)").click()
    self.driver.find_element(By.ID, "id_password").send_keys("Qwerty123")
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(4)").click()
    self.driver.find_element(By.ID, "myBtn").click()
    WebDriverWait(self.driver, 3000).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".btn-accept")))
    self.driver.find_element(By.CSS_SELECTOR, ".btn-accept").click()
    self.driver.find_element(By.ID, "LogOut").send_keys(Keys.ENTER)

  def test_153Poprawnewystawienieopiniibeztreci(self):
    self.driver.maximize_window()
    self.driver.get("http://127.0.0.1:8000/repertoire/")
    WebDriverWait(self.driver, 3000).until(expected_conditions.presence_of_element_located((By.ID, "cinemaSelector")))
    self.driver.find_element(By.ID, "cinemaSelector").click()
    dropdown = self.driver.find_element(By.ID, "cinemaSelector")
    dropdown.find_element(By.XPATH, "/html/body/header/nav/div/div/ul[2]/li[1]/form/a/select/option[2]").click()

    self.driver.find_element(By.ID, "LogIn").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("JanKowalski")
    self.driver.find_element(By.ID, "id_password").send_keys("Qwerty123")
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, "a > .card-img-top").click()
    WebDriverWait(self.driver, 4000).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "#review > i:nth-child(4)")))

    element_to_hover_over = self.driver.find_element(By.CSS_SELECTOR, "#review > i:nth-child(4)")
    hover = ActionChains(self.driver).move_to_element(element_to_hover_over)
    hover.perform()

    self.driver.find_element(By.CSS_SELECTOR, "#review > i:nth-child(4)").click()
    self.driver.find_element(By.ID, "textRatingDiv").click()
    self.driver.find_element(By.CSS_SELECTOR, ".textRatingSend").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "LogOut").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "LogIn").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "id_username").send_keys("admin")
    self.driver.find_element(By.ID, "id_password").send_keys("Koperek!1")
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "AdminPanel").click()
    self.driver.find_element(By.LINK_TEXT, "User opinions").click()
    self.driver.find_element(By.NAME, "_selected_action").click()
    assert self.driver.find_element(By.LINK_TEXT, "JanKowalski Batman - 3").text == "JanKowalski Batman - 3"
    self.driver.find_element(By.NAME, "action").click()
    dropdown = self.driver.find_element(By.NAME, "action")
    dropdown.find_element(By.XPATH, "//option[. = 'Delete selected user opinions']").click()
    self.driver.find_element(By.NAME, "index").click()
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(4)").click()
  
  def test_152PoprawneClipowanieTekstuPonad500znakow(self):
    self.driver.maximize_window()
    self.driver.get("http://127.0.0.1:8000/repertoire/")
    WebDriverWait(self.driver, 3000).until(expected_conditions.presence_of_element_located((By.ID, "cinemaSelector")))
    self.driver.find_element(By.ID, "cinemaSelector").click()
    dropdown = self.driver.find_element(By.ID, "cinemaSelector")
    dropdown.find_element(By.XPATH, "/html/body/header/nav/div/div/ul[2]/li[1]/form/a/select/option[2]").click()

    self.driver.find_element(By.ID, "LogIn").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("JanKowalski")
    self.driver.find_element(By.ID, "id_password").send_keys("Qwerty123")
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, "a > .card-img-top").click()
    WebDriverWait(self.driver, 4000).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "#review > i:nth-child(4)")))

    element_to_hover_over = self.driver.find_element(By.CSS_SELECTOR, "#review > i:nth-child(4)")
    hover = ActionChains(self.driver).move_to_element(element_to_hover_over)
    hover.perform()

    self.driver.find_element(By.CSS_SELECTOR, "#review > i:nth-child(4)").click()
    self.driver.find_element(By.ID, "textRating").send_keys("ZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakii")
    self.driver.find_element(By.CSS_SELECTOR, ".textRatingSend").send_keys(Keys.ENTER)
    assert self.driver.find_element(By.ID, "textRating").text == "ZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnakiZnaki"
    self.driver.find_element(By.ID, "LogOut").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "LogIn").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "id_username").send_keys("admin")
    self.driver.find_element(By.ID, "id_password").send_keys("Koperek!1")
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "AdminPanel").click()
    self.driver.find_element(By.LINK_TEXT, "User opinions").click()
    self.driver.find_element(By.NAME, "_selected_action").click()
    self.driver.find_element(By.NAME, "action").click()
    dropdown = self.driver.find_element(By.NAME, "action")
    dropdown.find_element(By.XPATH, "//option[. = 'Delete selected user opinions']").click()
    self.driver.find_element(By.NAME, "index").click()
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(4)").click()
  
  def test_173ZmianaAdresuEmailzbdnymidanymirneadresyemail(self):
    self.driver.maximize_window()
    self.driver.get("http://127.0.0.1:8000/repertoire/")
    
    self.driver.find_element(By.ID, "LogIn").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "id_username").send_keys("JanKowalski")
    self.driver.find_element(By.ID, "id_password").click()
    self.driver.find_element(By.ID, "id_password").send_keys("Qwerty123")
    self.driver.find_element(By.CSS_SELECTOR, ".bg-secondary").click()
    self.driver.find_element(By.ID, "UserCard").click()
    self.driver.find_element(By.LINK_TEXT, "Zmień swój adres email").click()
    self.driver.find_element(By.ID, "id_email1").click()
    self.driver.find_element(By.ID, "id_email1").send_keys("jankowalski3@wp.pl")
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(2)").click()
    self.driver.find_element(By.ID, "id_email2").click()
    self.driver.find_element(By.ID, "id_email2").send_keys("jan3@wp.pl")
    self.driver.find_element(By.ID, "id_password").click()
    self.driver.find_element(By.ID, "id_password").send_keys("Qwerty123")
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(4)").click()
    self.driver.find_element(By.ID, "myBtn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-accept").click()
    self.driver.find_element(By.CSS_SELECTOR, ".errorlist > li").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".errorlist > li").text == "Podane adresy muszą być takie same."
    self.driver.find_element(By.ID, "LogOut").send_keys(Keys.ENTER)
  
  def test_174ZmianaAdresuEmailzbdnymidanymiBrakwprowadzeniapierwszegoadresu(self):
    self.driver.maximize_window()
    self.driver.get("http://127.0.0.1:8000/repertoire/")

    self.driver.find_element(By.ID, "LogIn").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "id_username").send_keys("JanKowalski")
    self.driver.find_element(By.ID, "id_password").click()
    self.driver.find_element(By.ID, "id_password").send_keys("Qwerty123")
    self.driver.find_element(By.CSS_SELECTOR, ".bg-secondary").click()
    self.driver.find_element(By.ID, "UserCard").click()
    self.driver.find_element(By.LINK_TEXT, "Zmień swój adres email").click()
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(2)").click()
    self.driver.find_element(By.ID, "id_email2").click()
    self.driver.find_element(By.ID, "id_email2").send_keys("jan3@wp.pl")
    self.driver.find_element(By.ID, "id_password").click()
    self.driver.find_element(By.ID, "id_password").send_keys("Qwerty123")
    element = self.driver.find_element(By.ID, "myBtn")
    assert element.is_enabled() is False
    self.driver.find_element(By.ID, "LogOut").send_keys(Keys.ENTER)
  
  def test_175ZmianaAdresuEmailzbdnymidanymiBrakwprowadzeniadrugiegoadresu(self):
    self.driver.maximize_window()
    self.driver.get("http://127.0.0.1:8000/repertoire/")

    self.driver.find_element(By.ID, "LogIn").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "id_username").send_keys("JanKowalski")
    self.driver.find_element(By.ID, "id_password").click()
    self.driver.find_element(By.ID, "id_password").send_keys("Qwerty123")
    self.driver.find_element(By.CSS_SELECTOR, ".bg-secondary").click()
    self.driver.find_element(By.ID, "UserCard").click()
    self.driver.find_element(By.LINK_TEXT, "Zmień swój adres email").click()
    self.driver.find_element(By.ID, "id_email1").click()
    self.driver.find_element(By.ID, "id_email1").send_keys("jan3@wp.pl")
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(2)").click()
    self.driver.find_element(By.ID, "id_password").click()
    self.driver.find_element(By.ID, "id_password").send_keys("Qwerty123")
    element = self.driver.find_element(By.ID, "myBtn")
    assert element.is_enabled() is False
    self.driver.find_element(By.ID, "LogOut").send_keys(Keys.ENTER)
  
  def test_176ZmianaAdresuEmailzbdnymidanymiBrakwprowadzeniahasla(self):
    self.driver.maximize_window()
    self.driver.get("http://127.0.0.1:8000/repertoire/")

    self.driver.find_element(By.ID, "LogIn").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "id_username").send_keys("JanKowalski")
    self.driver.find_element(By.ID, "id_password").click()
    self.driver.find_element(By.ID, "id_password").send_keys("Qwerty123")
    self.driver.find_element(By.CSS_SELECTOR, ".bg-secondary").click()
    self.driver.find_element(By.ID, "UserCard").click()
    self.driver.find_element(By.LINK_TEXT, "Zmień swój adres email").click()
    self.driver.find_element(By.ID, "id_email1").click()
    self.driver.find_element(By.ID, "id_email1").send_keys("jan3@wp.pl")
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(2)").click()
    self.driver.find_element(By.ID, "id_email2").click()
    self.driver.find_element(By.ID, "id_email2").send_keys("jan3@wp.pl")
    element = self.driver.find_element(By.ID, "myBtn")
    assert element.is_enabled() is False
    self.driver.find_element(By.ID, "LogOut").send_keys(Keys.ENTER)

  def test_181Deaktywacjakontazpoprawnymhasem(self):
    self.driver.maximize_window()
    self.driver.get("http://127.0.0.1:8000/repertoire/")

    self.driver.find_element(By.ID, "LogIn").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("JanKowalski")
    self.driver.find_element(By.ID, "id_password").click()
    self.driver.find_element(By.ID, "id_password").send_keys("Qwerty123")
    self.driver.find_element(By.CSS_SELECTOR, ".bg-secondary").click()
    self.driver.find_element(By.ID, "UserCard").click()
    self.driver.find_element(By.LINK_TEXT, "Deaktywuj swoje konto").click()
    self.driver.find_element(By.ID, "id_password").click()
    self.driver.find_element(By.ID, "id_password").send_keys("Qwerty123")
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(2)").click()
    self.driver.find_element(By.ID, "myBtn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-accept").click()
    self.driver.find_element(By.ID, "LogIn").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("JanKowalski")
    self.driver.find_element(By.ID, "id_password").click()
    self.driver.find_element(By.ID, "id_password").send_keys("Qwerty123")
    self.driver.find_element(By.CSS_SELECTOR, ".bg-secondary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".item > p").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".item > p").text == "Twoja nazwa użytkownika lub hasło nie pasują. Spróbuj zalogować się jeszcze raz."
    self.driver.find_element(By.ID, "LogIn").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "id_username").clear()
    self.driver.find_element(By.ID, "id_username").send_keys("admin")
    self.driver.find_element(By.ID, "id_password").click()
    self.driver.find_element(By.ID, "id_password").send_keys("Koperek!1")
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "AdminPanel").click()
    self.driver.find_element(By.LINK_TEXT, "Users").click()
    self.driver.find_element(By.ID, "searchbar").click()
    self.driver.find_element(By.ID, "searchbar").send_keys("JanKowalski")
    self.driver.find_element(By.LINK_TEXT, "JanKowalski").click()
    assert self.driver.find_element(By.ID, "id_is_active").is_selected() is False
    self.driver.find_element(By.ID, "id_is_active").click()
    self.driver.find_element(By.NAME, "_save").click()
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(4)").click()
      
  def test_182Deaktywacjakontazbdnymhasem(self):
    self.driver.maximize_window()
    self.driver.get("http://127.0.0.1:8000/repertoire/")
    WebDriverWait(self.driver, 3000).until(expected_conditions.presence_of_element_located((By.ID, "cinemaSelector")))
    self.driver.find_element(By.ID, "cinemaSelector").click()
    dropdown = self.driver.find_element(By.ID, "cinemaSelector")

    self.driver.find_element(By.ID, "LogIn").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "id_username").send_keys("JanKowalski")
    self.driver.find_element(By.ID, "id_password").click()
    self.driver.find_element(By.ID, "id_password").send_keys("Qwerty123")
    self.driver.find_element(By.CSS_SELECTOR, ".bg-secondary").click()
    self.driver.find_element(By.ID, "UserCard").click()
    self.driver.find_element(By.LINK_TEXT, "Deaktywuj swoje konto").click()
    self.driver.find_element(By.ID, "id_password").click()
    self.driver.find_element(By.ID, "id_password").send_keys("Qwer")
    self.driver.find_element(By.CSS_SELECTOR, "form").click()
    self.driver.find_element(By.ID, "myBtn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-accept").click()
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(4)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(4)").text == "Błędne hasło."
    self.driver.find_element(By.ID, "LogOut").send_keys(Keys.ENTER)
  
  def test_619Dodanienowegofilmupoaktualizacjistrukturybazydanych(self):
    self.driver.maximize_window()
    self.driver.get("http://127.0.0.1:8000/repertoire/")

    self.driver.find_element(By.ID, "LogIn").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "id_username").send_keys("admin")
    self.driver.find_element(By.ID, "id_password").send_keys("Koperek!1")
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "AdminPanel").click()
    self.driver.find_element(By.LINK_TEXT, "Movies").click()
    self.driver.find_element(By.CSS_SELECTOR, "li > .addlink").click()
    self.driver.find_element(By.ID, "id_title").send_keys("Manchaster By The Sea")
    self.driver.find_element(By.ID, "id_description").send_keys("Wujek zostaje zmuszony do opieki nad nastoletnim bratankiem po śmierci jego ojca.")
    self.driver.find_element(By.ID, "id_productionCountry").send_keys("USA")
    self.driver.find_element(By.ID, "id_director").send_keys("Kenneth Lonergan")
    self.driver.find_element(By.ID, "id_screenwriter").send_keys("Kenneth Lonergan")
    self.driver.find_element(By.ID, "id_cast").send_keys("Casey Affleck, Lucas Hedges, Michelle Williams, Kyle Chandler")
    self.driver.find_element(By.ID, "id_trailer").clear()
    self.driver.find_element(By.ID, "id_trailer").send_keys("http://www.youtube.com/embed/gsVoD0pTge0")
    self.driver.find_element(By.CSS_SELECTOR, "#id_images > option:nth-child(10)").click()
    dropdown = self.driver.find_element(By.ID, "id_genre")
    dropdown.find_element(By.XPATH, "//option[. = 'Dramat']").click()
    self.driver.find_element(By.ID, "id_slug").clear()
    self.driver.find_element(By.ID, "id_slug").send_keys("manchasterbythesea")
    self.driver.find_element(By.ID, "id_releaseDate").clear()
    self.driver.find_element(By.ID, "id_releaseDate").send_keys("2016-01-23")
    self.driver.find_element(By.ID, "id_length").clear()
    self.driver.find_element(By.ID, "id_length").send_keys("137")
    self.driver.find_element(By.NAME, "_save").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) > .field-__str__ > a").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "id_title").click()
    self.driver.find_element(By.ID, "id_description").click()
    assert self.driver.find_element(By.ID, "id_description").text == "Wujek zostaje zmuszony do opieki nad nastoletnim bratankiem po śmierci jego ojca."
    self.driver.find_element(By.ID, "id_productionCountry").click()
    self.driver.find_element(By.ID, "id_director").click()
    self.driver.find_element(By.ID, "id_screenwriter").click()
    self.driver.find_element(By.ID, "id_cast").click()
    assert self.driver.find_element(By.ID, "id_cast").text == "Casey Affleck, Lucas Hedges, Michelle Williams, Kyle Chandler"
    self.driver.find_element(By.CSS_SELECTOR, ".field-trailer").click()
    self.driver.find_element(By.CSS_SELECTOR, "#id_images > option:nth-child(10)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "#id_images > option:nth-child(10)").text == "manchaster.jpg"
    self.driver.find_element(By.CSS_SELECTOR, "#id_genre > option:nth-child(13)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "#id_genre > option:nth-child(13)").text == "Dramat"
    self.driver.find_element(By.CSS_SELECTOR, ".field-slug > div").click()
    self.driver.find_element(By.CSS_SELECTOR, ".field-releaseDate > div").click()
    self.driver.find_element(By.CSS_SELECTOR, ".field-length > div").click()
    self.driver.find_element(By.LINK_TEXT, "Delete").click()
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(4)").click()
  
  def test_521Czasowewyznaczanieprojekcji(self):
    self.driver.maximize_window()
    self.driver.get("http://127.0.0.1:8000/repertoire/")

    self.driver.find_element(By.ID, "LogIn").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "id_username").send_keys("admin")
    self.driver.find_element(By.ID, "id_password").click()
    self.driver.find_element(By.ID, "id_password").send_keys("Koperek!1")
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "AdminPanel").click()
    self.driver.find_element(By.LINK_TEXT, "Showings").click()
    self.driver.find_element(By.CSS_SELECTOR, "li > .addlink").click()
    self.driver.find_element(By.ID, "id_movie").click()
    dropdown = self.driver.find_element(By.ID, "id_movie")
    dropdown.find_element(By.XPATH, "//option[. = 'Batman']").click()
    self.driver.find_element(By.ID, "id_hall").click()
    dropdown = self.driver.find_element(By.ID, "id_hall")
    dropdown.find_element(By.XPATH, "//option[. = 'Golden Screen AMW - Sala 1']").click()
    self.driver.find_element(By.ID, "id_showingDate").click()
    self.driver.find_element(By.ID, "id_showingDate").click()
    self.driver.find_element(By.ID, "id_showingDate").send_keys("2023-01-01")
    self.driver.find_element(By.CSS_SELECTOR, ".field-showingHour .related-widget-wrapper").click()
    self.driver.find_element(By.ID, "id_showingHour").click()
    dropdown = self.driver.find_element(By.ID, "id_showingHour")
    dropdown.find_element(By.XPATH, "//option[. = '12:00:00']").click()
    self.driver.find_element(By.ID, "id_futureDays").click()
    self.driver.find_element(By.CSS_SELECTOR, ".field-futureDays > div").click()
    self.driver.find_element(By.ID, "id_futureDays").send_keys("3")
    self.driver.find_element(By.CSS_SELECTOR, ".field-futureDays > div").click()
    self.driver.find_element(By.NAME, "_save").click()
    assert self.driver.find_element(By.LINK_TEXT, "Batman - Golden Screen AMW - Sala 1 2023-01-04 12:00:00").text == "Batman - Golden Screen AMW - Sala 1 2023-01-04 12:00:00"
    assert self.driver.find_element(By.LINK_TEXT, "Batman - Golden Screen AMW - Sala 1 2023-01-03 12:00:00").text == "Batman - Golden Screen AMW - Sala 1 2023-01-03 12:00:00"
    assert self.driver.find_element(By.LINK_TEXT, "Batman - Golden Screen AMW - Sala 1 2023-01-02 12:00:00").text == "Batman - Golden Screen AMW - Sala 1 2023-01-02 12:00:00"
    assert self.driver.find_element(By.LINK_TEXT, "Batman - Golden Screen AMW - Sala 1 2023-01-01 12:00:00").text == "Batman - Golden Screen AMW - Sala 1 2023-01-01 12:00:00"
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(4) .action-select").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3) .action-select").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) .action-select").click()
    self.driver.find_element(By.NAME, "_selected_action").click()
    self.driver.find_element(By.NAME, "action").click()
    dropdown = self.driver.find_element(By.NAME, "action")
    dropdown.find_element(By.XPATH, "//option[. = 'Delete selected Showings']").click()
    self.driver.find_element(By.NAME, "index").click()
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(7)").click()
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(4)").click()
  
  def test_522BedneczasowewyznaczanieprojekcjiUjemnyczasdni(self):
    self.driver.maximize_window()
    self.driver.get("http://127.0.0.1:8000/repertoire/")

    self.driver.find_element(By.ID, "LogIn").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "id_username").send_keys("admin")
    self.driver.find_element(By.ID, "id_password").click()
    self.driver.find_element(By.ID, "id_password").send_keys("Koperek!1")
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "AdminPanel").click()
    self.driver.find_element(By.LINK_TEXT, "Showings").click()
    self.driver.find_element(By.CSS_SELECTOR, "li > .addlink").click()
    self.driver.find_element(By.ID, "id_movie").click()
    dropdown = self.driver.find_element(By.ID, "id_movie")
    dropdown.find_element(By.XPATH, "//option[. = 'Batman']").click()
    self.driver.find_element(By.ID, "id_hall").click()
    dropdown = self.driver.find_element(By.ID, "id_hall")
    dropdown.find_element(By.XPATH, "//option[. = 'Golden Screen AMW - Sala 1']").click()
    self.driver.find_element(By.ID, "id_showingDate").click()
    self.driver.find_element(By.ID, "id_showingDate").click()
    self.driver.find_element(By.ID, "id_showingDate").send_keys("2023-01-01")
    self.driver.find_element(By.CSS_SELECTOR, ".field-showingHour .related-widget-wrapper").click()
    self.driver.find_element(By.ID, "id_showingHour").click()
    dropdown = self.driver.find_element(By.ID, "id_showingHour")
    dropdown.find_element(By.XPATH, "//option[. = '12:00:00']").click()
    element = self.driver.find_element(By.ID, "id_futureDays")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.ID, "id_futureDays")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.ID, "id_futureDays")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.ID, "id_futureDays").clear()
    self.driver.find_element(By.ID, "id_futureDays").send_keys("-1")
    self.driver.find_element(By.CSS_SELECTOR, ".field-futureDays > div").click()
    self.driver.find_element(By.NAME, "_save").click()
    self.driver.find_element(By.CSS_SELECTOR, ".errorlist").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "li").text == "Ensure this value is greater than or equal to 0."
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(4)").click()
  
  def test_331Wywietlenieurednionejocenyuytkownikw(self):
    self.driver.maximize_window()
    self.driver.get("http://127.0.0.1:8000/repertoire/")

    self.driver.find_element(By.ID, "LogIn").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "id_username").send_keys("admin")
    self.driver.find_element(By.ID, "id_password").send_keys("Koperek!1")
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "AdminPanel").click()
    self.driver.find_element(By.LINK_TEXT, "Movies").click()
    self.driver.find_element(By.CSS_SELECTOR, "li > .addlink").click()
    self.driver.find_element(By.ID, "id_title").send_keys("Manchaster By The Sea")
    self.driver.find_element(By.ID, "id_description").send_keys("Wujek zostaje zmuszony do opieki nad nastoletnim bratankiem po śmierci jego ojca.")
    self.driver.find_element(By.ID, "id_productionCountry").send_keys("USA")
    self.driver.find_element(By.ID, "id_director").send_keys("Kenneth Lonergan")
    self.driver.find_element(By.ID, "id_screenwriter").send_keys("Kenneth Lonergan")
    self.driver.find_element(By.ID, "id_cast").send_keys("Casey Affleck, Lucas Hedges, Michelle Williams, Kyle Chandler")
    self.driver.find_element(By.ID, "id_trailer").clear()
    self.driver.find_element(By.ID, "id_trailer").send_keys("http://www.youtube.com/embed/gsVoD0pTge0")
    self.driver.find_element(By.CSS_SELECTOR, "#id_images > option:nth-child(10)").click()
    dropdown = self.driver.find_element(By.ID, "id_genre")
    dropdown.find_element(By.XPATH, "//option[. = 'Dramat']").click()
    self.driver.find_element(By.ID, "id_slug").clear()
    self.driver.find_element(By.ID, "id_slug").send_keys("manchasterbythesea")
    self.driver.find_element(By.ID, "id_releaseDate").clear()
    self.driver.find_element(By.ID, "id_releaseDate").send_keys("2016-01-23")
    self.driver.find_element(By.ID, "id_length").clear()
    self.driver.find_element(By.ID, "id_length").send_keys("137")
    self.driver.find_element(By.NAME, "_save").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(4)").click()
    self.driver.find_element(By.ID, "LogIn").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "id_username").send_keys("JanKowalski")
    self.driver.find_element(By.ID, "id_password").send_keys("Qwerty123")
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)

    dropdown = self.driver.find_element(By.ID, "cinemaSelector")
    dropdown.find_element(By.XPATH, "/html/body/header/nav/div/div/ul[2]/li[1]/form/a/select/option[2]").click()

    self.driver.find_element(By.LINK_TEXT, "BIBLIOTEKA FILMÓW").click()
    self.driver.find_element(By.XPATH, "//span[contains(text(), \'Manchaster By The Sea\')]").click()
    self.driver.find_element(By.XPATH, "//*[@id=\"review\"]/i[3]").click()
    self.driver.find_element(By.CSS_SELECTOR, ".textRatingSend").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "LogOut").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "LogIn").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("admin")
    self.driver.find_element(By.ID, "id_password").send_keys("Koperek!1")
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)
    
    dropdown = self.driver.find_element(By.ID, "cinemaSelector")
    dropdown.find_element(By.XPATH, "/html/body/header/nav/div/div/ul[2]/li[1]/form/a/select/option[2]").click()

    self.driver.find_element(By.LINK_TEXT, "BIBLIOTEKA FILMÓW").click()
    self.driver.find_element(By.XPATH, "//span[contains(text(), \'Manchaster By The Sea\')]").click()
    self.driver.find_element(By.XPATH, "//*[@id=\"review\"]/i[2]").click()
    self.driver.find_element(By.CSS_SELECTOR, ".textRatingSend").send_keys(Keys.ENTER)
    self.driver.find_element(By.LINK_TEXT, "BIBLIOTEKA FILMÓW").click()
    assert self.driver.find_element(By.XPATH, "//span[contains(text(), \'Manchaster By The Sea\')]/../../div[5]/span[2]").text == "Ocena: 2,5"
    self.driver.find_element(By.ID, "AdminPanel").click()
    self.driver.find_element(By.LINK_TEXT, "Movies").click()
    self.driver.find_element(By.NAME, "_selected_action").click()
    self.driver.find_element(By.NAME, "action").click()
    dropdown = self.driver.find_element(By.NAME, "action")
    dropdown.find_element(By.XPATH, "//option[. = 'Delete selected movies']").click()
    self.driver.find_element(By.NAME, "index").click()
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(4)").click()
  
  def test_531Dodawaniesalikinowej(self):
    self.driver.maximize_window()
    self.driver.get("http://127.0.0.1:8000/repertoire/")

    self.driver.find_element(By.ID, "LogIn").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("admin")
    self.driver.find_element(By.ID, "id_password").send_keys("Koperek!1")
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "AdminPanel").click()
    self.driver.find_element(By.LINK_TEXT, "Halls").click()
    self.driver.find_element(By.CSS_SELECTOR, "li > .addlink").click()
    self.driver.find_element(By.ID, "id_name").send_keys("Hall 6")
    self.driver.find_element(By.ID, "btnAdd").click()
    self.driver.find_element(By.ID, "btnAddCol").click()
    self.driver.find_element(By.ID, "btnAddCol").click()
    self.driver.find_element(By.CSS_SELECTOR, ".mt").click()
    self.driver.find_element(By.NAME, "_save").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, "#result_list > tbody > tr:nth-child(1) > th > a").click()
    assert self.driver.find_element(By.ID, "id_seats").text == "[{\"index\": 0, \"seats\": [{\"id\": 0, \"isSeat\": true, \"isTaken\": false, \"selected\": false}, {\"id\": 1, \"isSeat\": true, \"isTaken\": false, \"selected\": false}]}, {\"index\": 1, \"seats\": [{\"id\": 0, \"isSeat\": true, \"isTaken\": false, \"selected\": false}, {\"id\": 1, \"isSeat\": true, \"isTaken\": false, \"selected\": false}]}]"
    self.driver.find_element(By.LINK_TEXT, "Delete").click()
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(4)").click()

  def test_532Bdnedodawaniesalikinowej(self):
    self.driver.maximize_window()
    self.driver.get("http://127.0.0.1:8000/repertoire/")

    self.driver.find_element(By.ID, "LogIn").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("admin")
    self.driver.find_element(By.ID, "id_password").send_keys("Koperek!1")
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "AdminPanel").click()
    self.driver.find_element(By.LINK_TEXT, "Halls").click()
    self.driver.find_element(By.CSS_SELECTOR, "li > .addlink").click()
    self.driver.find_element(By.ID, "id_name").send_keys("Hall 6")
    self.driver.find_element(By.ID, "btnAdd").click()
    self.driver.find_element(By.NAME, "_save").click()
    self.driver.find_element(By.CSS_SELECTOR, "li").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "li").text == "To pole jest wymagane."
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(4)").click()
    
  def test_332NiepoprawnewywietlenieurednionejocenyuytkownikwBrakocen(self):
    self.driver.maximize_window()
    self.driver.get("http://127.0.0.1:8000/repertoire/")

    self.driver.find_element(By.ID, "LogIn").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "id_username").send_keys("admin")
    self.driver.find_element(By.ID, "id_password").send_keys("Koperek!1")
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "AdminPanel").click()
    self.driver.find_element(By.LINK_TEXT, "Movies").click()
    self.driver.find_element(By.CSS_SELECTOR, "li > .addlink").click()
    self.driver.find_element(By.ID, "id_title").send_keys("Manchaster By The Sea")
    self.driver.find_element(By.ID, "id_description").send_keys("Wujek zostaje zmuszony do opieki nad nastoletnim bratankiem po śmierci jego ojca.")
    self.driver.find_element(By.ID, "id_productionCountry").send_keys("USA")
    self.driver.find_element(By.ID, "id_director").send_keys("Kenneth Lonergan")
    self.driver.find_element(By.ID, "id_screenwriter").send_keys("Kenneth Lonergan")
    self.driver.find_element(By.ID, "id_cast").send_keys("Casey Affleck, Lucas Hedges, Michelle Williams, Kyle Chandler")
    self.driver.find_element(By.ID, "id_trailer").clear()
    self.driver.find_element(By.ID, "id_trailer").send_keys("http://www.youtube.com/embed/gsVoD0pTge0")
    self.driver.find_element(By.CSS_SELECTOR, "#id_images > option:nth-child(10)").click()
    dropdown = self.driver.find_element(By.ID, "id_genre")
    dropdown.find_element(By.XPATH, "//option[. = 'Dramat']").click()
    self.driver.find_element(By.ID, "id_slug").clear()
    self.driver.find_element(By.ID, "id_slug").send_keys("manchasterbythesea")
    self.driver.find_element(By.ID, "id_releaseDate").clear()
    self.driver.find_element(By.ID, "id_releaseDate").send_keys("2016-01-23")
    self.driver.find_element(By.ID, "id_length").clear()
    self.driver.find_element(By.ID, "id_length").send_keys("137")
    self.driver.find_element(By.NAME, "_save").send_keys(Keys.ENTER)

    self.driver.find_element(By.CSS_SELECTOR, "#user-tools > a:nth-child(2)").click()

    dropdown = self.driver.find_element(By.ID, "cinemaSelector")
    dropdown.find_element(By.XPATH, "/html/body/header/nav/div/div/ul[2]/li[1]/form/a/select/option[2]").click()

    self.driver.find_element(By.LINK_TEXT, "BIBLIOTEKA FILMÓW").click()
    assert self.driver.find_element(By.XPATH, "//span[contains(text(), \'Manchaster By The Sea\')]/../../div[5]/span[2]").text == "Ocena: Brak"
    self.driver.find_element(By.ID, "AdminPanel").click()
    self.driver.find_element(By.LINK_TEXT, "Movies").click()
    self.driver.find_element(By.NAME, "_selected_action").click()
    self.driver.find_element(By.NAME, "action").click()
    dropdown = self.driver.find_element(By.NAME, "action")
    dropdown.find_element(By.XPATH, "//option[. = 'Delete selected movies']").click()
    self.driver.find_element(By.NAME, "index").click()
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(4)").click()

  def test_612DodanieFilmuIstniejacegoJuzWbazieDanych(self):
    self.driver.maximize_window()
    self.driver.get("http://127.0.0.1:8000/repertoire/")

    self.driver.find_element(By.ID, "LogIn").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "id_username").send_keys("admin")
    self.driver.find_element(By.ID, "id_password").send_keys("Koperek!1")
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "AdminPanel").click()
    self.driver.find_element(By.LINK_TEXT, "Movies").click()
    self.driver.find_element(By.CSS_SELECTOR, "li > .addlink").click()
    self.driver.find_element(By.ID, "id_title").send_keys("Manchaster By The Sea")
    self.driver.find_element(By.ID, "id_description").send_keys("Wujek zostaje zmuszony do opieki nad nastoletnim bratankiem po śmierci jego ojca.")
    self.driver.find_element(By.ID, "id_productionCountry").send_keys("USA")
    self.driver.find_element(By.ID, "id_director").send_keys("Kenneth Lonergan")
    self.driver.find_element(By.ID, "id_screenwriter").send_keys("Kenneth Lonergan")
    self.driver.find_element(By.ID, "id_cast").send_keys("Casey Affleck, Lucas Hedges, Michelle Williams, Kyle Chandler")
    self.driver.find_element(By.ID, "id_trailer").clear()
    self.driver.find_element(By.ID, "id_trailer").send_keys("http://www.youtube.com/embed/gsVoD0pTge0")
    self.driver.find_element(By.CSS_SELECTOR, "#id_images > option:nth-child(10)").click()
    dropdown = self.driver.find_element(By.ID, "id_genre")
    dropdown.find_element(By.XPATH, "//option[. = 'Dramat']").click()
    self.driver.find_element(By.ID, "id_slug").clear()
    self.driver.find_element(By.ID, "id_slug").send_keys("manchasterbythesea")
    self.driver.find_element(By.ID, "id_releaseDate").clear()
    self.driver.find_element(By.ID, "id_releaseDate").send_keys("2016-01-23")
    self.driver.find_element(By.ID, "id_length").clear()
    self.driver.find_element(By.ID, "id_length").send_keys("137")
    self.driver.find_element(By.NAME, "_save").send_keys(Keys.ENTER)
    self.driver.find_element(By.LINK_TEXT, "Movies").click()
    self.driver.find_element(By.CSS_SELECTOR, "li > .addlink").click()
    self.driver.find_element(By.ID, "id_title").send_keys("Manchaster By The Sea")
    self.driver.find_element(By.ID, "id_description").send_keys("Wujek zostaje zmuszony do opieki nad nastoletnim bratankiem po śmierci jego ojca.")
    self.driver.find_element(By.ID, "id_productionCountry").send_keys("USA")
    self.driver.find_element(By.ID, "id_director").send_keys("Kenneth Lonergan")
    self.driver.find_element(By.ID, "id_screenwriter").send_keys("Kenneth Lonergan")
    self.driver.find_element(By.ID, "id_cast").send_keys("Casey Affleck, Lucas Hedges, Michelle Williams, Kyle Chandler")
    self.driver.find_element(By.ID, "id_trailer").clear()
    self.driver.find_element(By.ID, "id_trailer").send_keys("http://www.youtube.com/embed/gsVoD0pTge0")
    self.driver.find_element(By.CSS_SELECTOR, "#id_images > option:nth-child(10)").click()
    dropdown = self.driver.find_element(By.ID, "id_genre")
    dropdown.find_element(By.XPATH, "//option[. = 'Dramat']").click()
    self.driver.find_element(By.ID, "id_slug").clear()
    self.driver.find_element(By.ID, "id_slug").send_keys("manchasterbythesea")
    self.driver.find_element(By.ID, "id_releaseDate").clear()
    self.driver.find_element(By.ID, "id_releaseDate").send_keys("2016-01-23")
    self.driver.find_element(By.ID, "id_length").clear()
    self.driver.find_element(By.ID, "id_length").send_keys("137")
    self.driver.find_element(By.NAME, "_save").send_keys(Keys.ENTER)
    assert self.driver.find_element(By.XPATH, "/html/body/div[1]/div[3]/div/div[1]/div/form/div/ul").text == "Movie with this Title and ReleaseDate already exists."
    self.driver.find_element(By.XPATH, "/html/body/div[1]/div[3]/nav/div[3]/table/tbody/tr[3]/th/a").click()
    self.driver.find_element(By.XPATH, " /html/body/div/div[3]/div/div[1]/div/div/div/form/div[2]/table/tbody/tr[1]/th/a").click()
    self.driver.find_element(By.LINK_TEXT, "Delete").click()
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(4)").click()

  def test_613dodanieFilmuBezNazwy(self):
    self.driver.maximize_window()
    self.driver.get("http://127.0.0.1:8000/repertoire/")

    self.driver.find_element(By.ID, "LogIn").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "id_username").send_keys("admin")
    self.driver.find_element(By.ID, "id_password").send_keys("Koperek!1")
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "AdminPanel").click()
    self.driver.find_element(By.LINK_TEXT, "Movies").click()
    self.driver.find_element(By.CSS_SELECTOR, "li > .addlink").click()
    self.driver.find_element(By.ID, "id_title").send_keys(" ")
    self.driver.find_element(By.ID, "id_description").send_keys("Wujek zostaje zmuszony do opieki nad nastoletnim bratankiem po śmierci jego ojca.")
    self.driver.find_element(By.ID, "id_productionCountry").send_keys("USA")
    self.driver.find_element(By.ID, "id_director").send_keys("Kenneth Lonergan")
    self.driver.find_element(By.ID, "id_screenwriter").send_keys("Kenneth Lonergan")
    self.driver.find_element(By.ID, "id_cast").send_keys("Casey Affleck, Lucas Hedges, Michelle Williams, Kyle Chandler")
    self.driver.find_element(By.ID, "id_trailer").clear()
    self.driver.find_element(By.ID, "id_trailer").send_keys("http://www.youtube.com/embed/gsVoD0pTge0")
    self.driver.find_element(By.CSS_SELECTOR, "#id_images > option:nth-child(10)").click()
    dropdown = self.driver.find_element(By.ID, "id_genre")
    dropdown.find_element(By.XPATH, "//option[. = 'Dramat']").click()
    self.driver.find_element(By.ID, "id_slug").clear()
    self.driver.find_element(By.ID, "id_slug").send_keys("manchasterbythesea")
    self.driver.find_element(By.ID, "id_releaseDate").clear()
    self.driver.find_element(By.ID, "id_releaseDate").send_keys("2016-01-23")
    self.driver.find_element(By.ID, "id_length").clear()
    self.driver.find_element(By.ID, "id_length").send_keys("137")
    self.driver.find_element(By.NAME, "_save").send_keys(Keys.ENTER)
    assert self.driver.find_element_by_class_name('errorlist').text == "To pole jest wymagane."
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(4)").click()

  def test_614dodanieFilmuBezOpisu(self):
    self.driver.maximize_window()
    self.driver.get("http://127.0.0.1:8000/repertoire/")

    self.driver.find_element(By.ID, "LogIn").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "id_username").send_keys("admin")
    self.driver.find_element(By.ID, "id_password").send_keys("Koperek!1")
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "AdminPanel").click()
    self.driver.find_element(By.LINK_TEXT, "Movies").click()
    self.driver.find_element(By.CSS_SELECTOR, "li > .addlink").click()
    self.driver.find_element(By.ID, "id_title").send_keys("Manchaster By The Sea")
    self.driver.find_element(By.ID, "id_description").send_keys(" ")
    self.driver.find_element(By.ID, "id_productionCountry").send_keys("USA")
    self.driver.find_element(By.ID, "id_director").send_keys("Kenneth Lonergan")
    self.driver.find_element(By.ID, "id_screenwriter").send_keys("Kenneth Lonergan")
    self.driver.find_element(By.ID, "id_cast").send_keys("Casey Affleck, Lucas Hedges, Michelle Williams, Kyle Chandler")
    self.driver.find_element(By.ID, "id_trailer").clear()
    self.driver.find_element(By.ID, "id_trailer").send_keys("http://www.youtube.com/embed/gsVoD0pTge0")
    self.driver.find_element(By.CSS_SELECTOR, "#id_images > option:nth-child(10)").click()
    dropdown = self.driver.find_element(By.ID, "id_genre")
    dropdown.find_element(By.XPATH, "//option[. = 'Dramat']").click()
    self.driver.find_element(By.ID, "id_slug").clear()
    self.driver.find_element(By.ID, "id_slug").send_keys("manchasterbythesea")
    self.driver.find_element(By.ID, "id_releaseDate").clear()
    self.driver.find_element(By.ID, "id_releaseDate").send_keys("2016-01-23")
    self.driver.find_element(By.ID, "id_length").clear()
    self.driver.find_element(By.ID, "id_length").send_keys("137")
    self.driver.find_element(By.NAME, "_save").send_keys(Keys.ENTER)
    assert self.driver.find_element_by_class_name('errorlist').text == "To pole jest wymagane."
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(4)").click()

  def test_615dodanieFilmuBezZdjecia(self):
    self.driver.maximize_window()
    self.driver.get("http://127.0.0.1:8000/repertoire/")

    self.driver.find_element(By.ID, "LogIn").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "id_username").send_keys("admin")
    self.driver.find_element(By.ID, "id_password").send_keys("Koperek!1")
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "AdminPanel").click()
    self.driver.find_element(By.LINK_TEXT, "Movies").click()
    self.driver.find_element(By.CSS_SELECTOR, "li > .addlink").click()
    self.driver.find_element(By.ID, "id_title").send_keys("Manchaster By The Sea")
    self.driver.find_element(By.ID, "id_description").send_keys("Wujek zostaje zmuszony do opieki nad nastoletnim bratankiem po śmierci jego ojca.")
    self.driver.find_element(By.ID, "id_productionCountry").send_keys("USA")
    self.driver.find_element(By.ID, "id_director").send_keys("Kenneth Lonergan")
    self.driver.find_element(By.ID, "id_screenwriter").send_keys("Kenneth Lonergan")
    self.driver.find_element(By.ID, "id_cast").send_keys("Casey Affleck, Lucas Hedges, Michelle Williams, Kyle Chandler")
    self.driver.find_element(By.ID, "id_trailer").clear()
    self.driver.find_element(By.ID, "id_trailer").send_keys("http://www.youtube.com/embed/gsVoD0pTge0")
    #self.driver.find_element(By.CSS_SELECTOR, "#id_images > option:nth-child(14)").click()
    dropdown = self.driver.find_element(By.ID, "id_genre")
    dropdown.find_element(By.XPATH, "//option[. = 'Dramat']").click()
    self.driver.find_element(By.ID, "id_slug").clear()
    self.driver.find_element(By.ID, "id_slug").send_keys("manchasterbythesea")
    self.driver.find_element(By.ID, "id_releaseDate").clear()
    self.driver.find_element(By.ID, "id_releaseDate").send_keys("2016-01-23")
    self.driver.find_element(By.ID, "id_length").clear()
    self.driver.find_element(By.ID, "id_length").send_keys("137")
    self.driver.find_element(By.NAME, "_save").send_keys(Keys.ENTER)
    assert self.driver.find_element_by_class_name('errorlist').text == "To pole jest wymagane."
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(4)").click()

  def test_616dodanieFilmuBezSlugu(self):
    self.driver.maximize_window()
    self.driver.get("http://127.0.0.1:8000/repertoire/")

    self.driver.find_element(By.ID, "LogIn").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "id_username").send_keys("admin")
    self.driver.find_element(By.ID, "id_password").send_keys("Koperek!1")
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "AdminPanel").click()
    self.driver.find_element(By.LINK_TEXT, "Movies").click()
    self.driver.find_element(By.CSS_SELECTOR, "li > .addlink").click()
    self.driver.find_element(By.ID, "id_title").send_keys("Manchaster By The Sea")
    self.driver.find_element(By.ID, "id_description").send_keys("Wujek zostaje zmuszony do opieki nad nastoletnim bratankiem po śmierci jego ojca.")
    self.driver.find_element(By.ID, "id_productionCountry").send_keys("USA")
    self.driver.find_element(By.ID, "id_director").send_keys("Kenneth Lonergan")
    self.driver.find_element(By.ID, "id_screenwriter").send_keys("Kenneth Lonergan")
    self.driver.find_element(By.ID, "id_cast").send_keys("Casey Affleck, Lucas Hedges, Michelle Williams, Kyle Chandler")
    self.driver.find_element(By.ID, "id_trailer").clear()
    self.driver.find_element(By.ID, "id_trailer").send_keys("http://www.youtube.com/embed/gsVoD0pTge0")
    self.driver.find_element(By.CSS_SELECTOR, "#id_images > option:nth-child(10)").click()
    dropdown = self.driver.find_element(By.ID, "id_genre")
    dropdown.find_element(By.XPATH, "//option[. = 'Dramat']").click()
    self.driver.find_element(By.ID, "id_slug").clear()
    #self.driver.find_element(By.ID, "id_slug").send_keys("manchasterbythesea")
    self.driver.find_element(By.ID, "id_releaseDate").clear()
    self.driver.find_element(By.ID, "id_releaseDate").send_keys("2016-01-23")
    self.driver.find_element(By.ID, "id_length").clear()
    self.driver.find_element(By.ID, "id_length").send_keys("137")
    self.driver.find_element(By.NAME, "_save").send_keys(Keys.ENTER)
    assert self.driver.find_element_by_class_name('errorlist').text == "To pole jest wymagane."
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(4)").click()

  def test_617dodanieFilmuZujemnymCzasem(self):
    self.driver.maximize_window()
    self.driver.get("http://127.0.0.1:8000/repertoire/")

    self.driver.find_element(By.ID, "LogIn").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "id_username").send_keys("admin")
    self.driver.find_element(By.ID, "id_password").send_keys("Koperek!1")
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "AdminPanel").click()
    self.driver.find_element(By.LINK_TEXT, "Movies").click()
    self.driver.find_element(By.CSS_SELECTOR, "li > .addlink").click()
    self.driver.find_element(By.ID, "id_title").send_keys("Manchaster By The Sea")
    self.driver.find_element(By.ID, "id_description").send_keys("Wujek zostaje zmuszony do opieki nad nastoletnim bratankiem po śmierci jego ojca.")
    self.driver.find_element(By.ID, "id_productionCountry").send_keys("USA")
    self.driver.find_element(By.ID, "id_director").send_keys("Kenneth Lonergan")
    self.driver.find_element(By.ID, "id_screenwriter").send_keys("Kenneth Lonergan")
    self.driver.find_element(By.ID, "id_cast").send_keys("Casey Affleck, Lucas Hedges, Michelle Williams, Kyle Chandler")
    self.driver.find_element(By.ID, "id_trailer").clear()
    self.driver.find_element(By.ID, "id_trailer").send_keys("http://www.youtube.com/embed/gsVoD0pTge0")
    self.driver.find_element(By.CSS_SELECTOR, "#id_images > option:nth-child(10)").click()
    dropdown = self.driver.find_element(By.ID, "id_genre")
    dropdown.find_element(By.XPATH, "//option[. = 'Dramat']").click()
    self.driver.find_element(By.ID, "id_slug").clear()
    self.driver.find_element(By.ID, "id_slug").send_keys("manchasterbythesea")
    self.driver.find_element(By.ID, "id_releaseDate").clear()
    self.driver.find_element(By.ID, "id_releaseDate").send_keys("2016-01-23")
    self.driver.find_element(By.ID, "id_length").clear()
    self.driver.find_element(By.ID, "id_length").send_keys("-5")
    self.driver.find_element(By.NAME, "_save").send_keys(Keys.ENTER)
    assert self.driver.find_element_by_class_name('errorlist').text == "Ensure this value is greater than or equal to 5."
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(4)").click()

  def test_541PoprawneEdytowanieSaliKinowej(self):
    self.driver.maximize_window()
    self.driver.get("http://127.0.0.1:8000/repertoire/")

    self.driver.find_element(By.ID, "LogIn").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "id_username").send_keys("admin")
    self.driver.find_element(By.ID, "id_password").send_keys("Koperek!1")
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "AdminPanel").click()
    self.driver.find_element(By.LINK_TEXT, "Halls").click()
    self.driver.find_element(By.CSS_SELECTOR, "li > .addlink").click()
    self.driver.find_element(By.ID, "id_name").send_keys("Hall 6")
    self.driver.find_element(By.ID, "btnAdd").click()
    self.driver.find_element(By.ID, "btnAddCol").click()
    self.driver.find_element(By.ID, "btnAddCol").click()
    self.driver.find_element(By.CSS_SELECTOR, "input.button:nth-child(7)").click()
    self.driver.find_element(By.NAME, "_save").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, "#result_list > tbody > tr:nth-child(1) > th > a").click()
    self.driver.find_element(By.CSS_SELECTOR, ".field-seats").click()
    assert self.driver.find_element(By.ID, "id_seats").text == "[{\"index\": 0, \"seats\": [{\"id\": 0, \"isSeat\": true, \"isTaken\": false, \"selected\": false}, {\"id\": 1, \"isSeat\": true, \"isTaken\": false, \"selected\": false}]}, {\"index\": 1, \"seats\": [{\"id\": 0, \"isSeat\": true, \"isTaken\": false, \"selected\": false}, {\"id\": 1, \"isSeat\": true, \"isTaken\": false, \"selected\": false}]}]"
    self.driver.find_element(By.ID, "btnAdd").click()
    self.driver.find_element(By.ID, "btnAdd").click()
    self.driver.find_element(By.ID, "btnAddCol").click()
    self.driver.find_element(By.ID, "btnAddCol").click()
    self.driver.find_element(By.CSS_SELECTOR, ".mt").click()
    self.driver.find_element(By.NAME, "_save").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, "#result_list > tbody > tr:nth-child(1) > th > a").click()
    self.driver.find_element(By.CSS_SELECTOR, ".field-seats").click()
    self.driver.find_element(By.NAME, "_save").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, "#result_list > tbody > tr:nth-child(1) > th > a").click()
    assert self.driver.find_element(By.ID, "id_seats").text == "[{\"index\": 0, \"seats\": [{\"id\": 0, \"isSeat\": true, \"isTaken\": false, \"selected\": false}, {\"id\": 1, \"isSeat\": true, \"isTaken\": false, \"selected\": false}, {\"id\": 2, \"isSeat\": true, \"isTaken\": false, \"selected\": false}, {\"id\": 3, \"isSeat\": true, \"isTaken\": false, \"selected\": false}]}, {\"index\": 1, \"seats\": [{\"id\": 0, \"isSeat\": true, \"isTaken\": false, \"selected\": false}, {\"id\": 1, \"isSeat\": true, \"isTaken\": false, \"selected\": false}, {\"id\": 2, \"isSeat\": true, \"isTaken\": false, \"selected\": false}, {\"id\": 3, \"isSeat\": true, \"isTaken\": false, \"selected\": false}]}, {\"index\": 2, \"seats\": [{\"id\": 0, \"isSeat\": true, \"isTaken\": false, \"selected\": false}, {\"id\": 1, \"isSeat\": true, \"isTaken\": false, \"selected\": false}, {\"id\": 2, \"isSeat\": true, \"isTaken\": false, \"selected\": false}, {\"id\": 3, \"isSeat\": true, \"isTaken\": false, \"selected\": false}]}, {\"index\": 3, \"seats\": [{\"id\": 0, \"isSeat\": true, \"isTaken\": false, \"selected\": false}, {\"id\": 1, \"isSeat\": true, \"isTaken\": false, \"selected\": false}, {\"id\": 2, \"isSeat\": true, \"isTaken\": false, \"selected\": false}, {\"id\": 3, \"isSeat\": true, \"isTaken\": false, \"selected\": false}]}]"
    self.driver.find_element(By.LINK_TEXT, "Delete").click()
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(4)").click()

  def test_542BledneEdytowanieSaliKinowej(self):
    self.driver.maximize_window()
    self.driver.get("http://127.0.0.1:8000/repertoire/")

    self.driver.find_element(By.ID, "LogIn").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "id_username").send_keys("admin")
    self.driver.find_element(By.ID, "id_password").send_keys("Koperek!1")
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "AdminPanel").click()
    self.driver.find_element(By.LINK_TEXT, "Halls").click()
    self.driver.find_element(By.CSS_SELECTOR, "li > .addlink").click()
    self.driver.find_element(By.ID, "id_name").send_keys("Hall 6")
    self.driver.find_element(By.ID, "btnAdd").click()
    self.driver.find_element(By.ID, "btnAddCol").click()
    self.driver.find_element(By.ID, "btnAddCol").click()
    self.driver.find_element(By.CSS_SELECTOR, "input.button:nth-child(7)").click()
    self.driver.find_element(By.NAME, "_save").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, "#result_list > tbody > tr:nth-child(1) > th > a").click()
    self.driver.find_element(By.CSS_SELECTOR, ".field-seats").click()
    assert self.driver.find_element(By.ID, "id_seats").text == "[{\"index\": 0, \"seats\": [{\"id\": 0, \"isSeat\": true, \"isTaken\": false, \"selected\": false}, {\"id\": 1, \"isSeat\": true, \"isTaken\": false, \"selected\": false}]}, {\"index\": 1, \"seats\": [{\"id\": 0, \"isSeat\": true, \"isTaken\": false, \"selected\": false}, {\"id\": 1, \"isSeat\": true, \"isTaken\": false, \"selected\": false}]}]"
    self.driver.find_element(By.ID, "btnRemRow").click()
    self.driver.find_element(By.ID, "btnRemRow").click()
    self.driver.find_element(By.ID, "btnRemCol").click()
    self.driver.find_element(By.ID, "btnRemCol").click()
    self.driver.find_element(By.CSS_SELECTOR, ".mt").click()
    self.driver.find_element(By.NAME, "_save").send_keys(Keys.ENTER)
    assert self.driver.find_element_by_class_name('errorlist').text == "To pole jest wymagane."
    self.driver.find_element(By.LINK_TEXT, "Delete").click()
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(4)").click()
  
  def test_511Dodawanienowegoseansu(self):
    self.driver.maximize_window()
    self.driver.get("http://127.0.0.1:8000/repertoire/")

    self.driver.find_element(By.ID, "LogIn").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "id_username").send_keys("admin")
    self.driver.find_element(By.ID, "id_password").send_keys("Koperek!1")
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "AdminPanel").click()
    self.driver.find_element(By.LINK_TEXT, "Showings").click()
    self.driver.find_element(By.CSS_SELECTOR, "li > .addlink").click()
    self.driver.find_element(By.ID, "id_movie").click()
    dropdown = self.driver.find_element(By.ID, "id_movie")
    dropdown.find_element(By.XPATH, "//option[. = 'Batman']").click()
    self.driver.find_element(By.ID, "id_hall").click()
    dropdown = self.driver.find_element(By.ID, "id_hall")
    dropdown.find_element(By.XPATH, "//option[. = 'Golden Screen Gdańsk - Sala 1']").click()
    self.driver.find_element(By.ID, "id_showingDate").click()
    self.driver.find_element(By.ID, "id_showingDate").send_keys("2022-08-11")
    self.driver.find_element(By.ID, "id_showingHour").click()
    dropdown = self.driver.find_element(By.ID, "id_showingHour")
    dropdown.find_element(By.XPATH, "//option[. = '19:00:00']").click()
    self.driver.find_element(By.NAME, "_save").click()
    assert self.driver.find_element(By.LINK_TEXT, "Batman - Golden Screen Gdańsk - Sala 1 2022-08-11 19:00:00").text == "Batman - Golden Screen Gdańsk - Sala 1 2022-08-11 19:00:00"
    self.driver.find_element(By.LINK_TEXT, "Batman - Golden Screen Gdańsk - Sala 1 2022-08-11 19:00:00").click()
    self.driver.find_element(By.LINK_TEXT, "Delete").click()
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(4)").click()

  def test_512Powtornedodawanienowegoseansu(self):
    self.driver.maximize_window()
    self.driver.get("http://127.0.0.1:8000/repertoire/")

    self.driver.find_element(By.ID, "LogIn").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "id_username").send_keys("admin")
    self.driver.find_element(By.ID, "id_password").send_keys("Koperek!1")
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "AdminPanel").click()
    self.driver.find_element(By.LINK_TEXT, "Showings").click()
    self.driver.find_element(By.CSS_SELECTOR, "li > .addlink").click()
    self.driver.find_element(By.ID, "id_movie").click()
    dropdown = self.driver.find_element(By.ID, "id_movie")
    dropdown.find_element(By.XPATH, "//option[. = 'Batman']").click()
    self.driver.find_element(By.ID, "id_hall").click()
    dropdown = self.driver.find_element(By.ID, "id_hall")
    dropdown.find_element(By.XPATH, "//option[. = 'Golden Screen Gdańsk - Sala 1']").click()
    self.driver.find_element(By.ID, "id_showingDate").click()
    self.driver.find_element(By.ID, "id_showingDate").send_keys("2022-08-11")
    self.driver.find_element(By.ID, "id_showingHour").click()
    dropdown = self.driver.find_element(By.ID, "id_showingHour")
    dropdown.find_element(By.XPATH, "//option[. = '19:00:00']").click()
    self.driver.find_element(By.NAME, "_save").click()
    self.driver.find_element(By.CSS_SELECTOR, "li > .addlink").click()
    self.driver.find_element(By.ID, "id_movie").click()
    dropdown = self.driver.find_element(By.ID, "id_movie")
    dropdown.find_element(By.XPATH, "//option[. = 'Batman']").click()
    self.driver.find_element(By.ID, "id_hall").click()
    dropdown = self.driver.find_element(By.ID, "id_hall")
    dropdown.find_element(By.XPATH, "//option[. = 'Golden Screen Gdańsk - Sala 1']").click()
    self.driver.find_element(By.ID, "id_showingDate").click()
    self.driver.find_element(By.ID, "id_showingDate").send_keys("2022-08-11")
    self.driver.find_element(By.ID, "id_showingHour").click()
    dropdown = self.driver.find_element(By.ID, "id_showingHour")
    dropdown.find_element(By.XPATH, "//option[. = '19:00:00']").click()
    self.driver.find_element(By.NAME, "_save").click()
    assert self.driver.find_element(By.XPATH, '/html/body/div[1]/div[3]/div/div[1]/div/form/div/ul/li[1]').text == "Showing with this Movie, Hall, ShowingDate and ShowingHour already exists."
    self.driver.find_element(By.XPATH, "/html/body/div[1]/div[2]/a[3]").click()
    self.driver.find_element(By.LINK_TEXT, "Batman - Golden Screen Gdańsk - Sala 1 2022-08-11 19:00:00").click()
    self.driver.find_element(By.LINK_TEXT, "Delete").click()
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(4)").click()

  def test_513Blednedodanienowegoseansuzprzeszladata(self):
    self.driver.maximize_window()
    self.driver.get("http://127.0.0.1:8000/repertoire/")

    self.driver.find_element(By.ID, "LogIn").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "id_username").send_keys("admin")
    self.driver.find_element(By.ID, "id_password").send_keys("Koperek!1")
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "AdminPanel").click()
    self.driver.find_element(By.LINK_TEXT, "Showings").click()
    self.driver.find_element(By.CSS_SELECTOR, "li > .addlink").click()
    self.driver.find_element(By.ID, "id_movie").click()
    dropdown = self.driver.find_element(By.ID, "id_movie")
    dropdown.find_element(By.XPATH, "//option[. = 'Batman']").click()
    self.driver.find_element(By.ID, "id_hall").click()
    dropdown = self.driver.find_element(By.ID, "id_hall")
    dropdown.find_element(By.XPATH, "//option[. = 'Golden Screen Gdańsk - Sala 1']").click()
    self.driver.find_element(By.ID, "id_showingDate").click()
    self.driver.find_element(By.ID, "id_showingDate").send_keys("2022-03-08")
    self.driver.find_element(By.ID, "id_showingHour").click()
    dropdown = self.driver.find_element(By.ID, "id_showingHour")
    dropdown.find_element(By.XPATH, "//option[. = '19:00:00']").click()
    self.driver.find_element(By.NAME, "_save").click()
    assert self.driver.find_element(By.XPATH, '/html/body/div[1]/div[3]/div/div[1]/div/form/div/p').text == "Please correct the error below."
    self.driver.find_element(By.XPATH, "/html/body/div[1]/div[3]/nav/div[5]/table/tbody/tr[2]/th/a").click()
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(4)").click()

  def test_633DodanieNowejPlacowkiKinaBezAdresu(self):
    self.driver.maximize_window()
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.find_element(By.ID, "LogIn").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "id_username").send_keys("admin")
    self.driver.find_element(By.ID, "id_password").send_keys("Koperek!1")
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "AdminPanel").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, ".model-cinema .addlink").click()
    self.driver.find_element(By.ID, "id_name").send_keys("Golden Screen Sopot")
    self.driver.find_element(By.NAME, "_save").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".errorlist > li").text == "To pole jest wymagane."
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(4)").click()

  def test_421WyswietleniePinuLokalizacji(self):
    self.driver.maximize_window()
    self.driver.get("http://127.0.0.1:8000/")
    WebDriverWait(self.driver, 5000).until(expected_conditions.visibility_of_element_located((By.XPATH, "/html/body/div/div/div/div/div/div/div[2]/div[2]/div/div[3]/div[1]")))
    self.driver.find_element_by_xpath('/html/body/div/div/div/div/div/div/div[2]/div[2]/div/div[3]/div[1]')

  def test_261WyswietlenieAdresuPlacowki(self):
    self.driver.maximize_window()
    self.driver.get("http://127.0.0.1:8000/repertoire/")
    WebDriverWait(self.driver, 3000).until(expected_conditions.presence_of_element_located((By.ID, "cinemaSelector")))
    self.driver.find_element(By.ID, "cinemaSelector").click()
    dropdown = self.driver.find_element(By.ID, "cinemaSelector")
    dropdown.find_element(By.XPATH, "/html/body/header/nav/div/div/ul[2]/li[1]/form/a/select/option[2]").click()
    self.driver.find_element_by_xpath("//header[@title='Inżyniera Jana Śmidowicza 48, Gdynia, Polska']")